version: '3.8'

services:
  app:
    build: .
    container_name: control_asistencia
    ports:
      - "5000:5000"
    volumes:
      - ./socios.csv:/app/socios.csv
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    command: python3 app.py
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 